/**
 * Writes out/sw.js after `next build`.
 *
 * The till has to *boot* offline, not just write offline: Firestore's queued
 * writes survive a reload, but with `output: "export"` and no service worker
 * the tab can't load index.html or its chunks without a network, so a cashier
 * who reloads mid-outage loses the app entirely. This precaches the whole
 * export — it is ~2 MB — and serves it cache-first.
 *
 * Generated rather than hand-written because the chunk filenames are content-
 * hashed at build time and can't be listed ahead of time.
 */

import { createHash } from "node:crypto";
import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const OUT_DIR = path.join(process.cwd(), "out");
const SW_PATH = path.join(OUT_DIR, "sw.js");

async function listFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const full = path.join(dir, entry.name);
      return entry.isDirectory() ? listFiles(full) : [full];
    }),
  );
  return files.flat();
}

const files = await listFiles(OUT_DIR);
const urls = files
  .map((f) => "/" + path.relative(OUT_DIR, f).split(path.sep).join("/"))
  .filter((u) => u !== "/sw.js")
  .sort();

// Hashing the file list gives a new cache name on every deploy — which is
// exactly when the old cache must be thrown away.
const version = createHash("sha1").update(urls.join("\n")).digest("hex").slice(0, 12);

const sw = `// Generated by scripts/generate-sw.mjs — do not edit by hand.
const CACHE = "bakeshop-${version}";
/**
 * Product photos, kept in their own cache so a deploy doesn't wipe them —
 * they come from Firebase Storage, not from the build, and re-downloading
 * every picture after each release would defeat the point on shop wifi.
 */
const IMAGE_CACHE = "bakeshop-images";
const IMAGE_HOSTS = ["firebasestorage.googleapis.com", "firebasestorage.app"];
/** Enough for a few hundred products; oldest are dropped first. */
const MAX_IMAGES = 400;
/**
 * How long a page load waits for the network before falling back to the cached
 * shell. Long enough to beat shop wifi, short enough that an outage doesn't
 * feel like a hang.
 */
const NAVIGATION_TIMEOUT_MS = 2500;
const PRECACHE = ${JSON.stringify(urls, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // One at a time, ignoring failures: a single missing file must not leave
      // the till with no offline shell at all.
      await Promise.all(PRECACHE.map((url) => cache.add(url).catch(() => {})));
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((n) => n.startsWith("bakeshop-") && n !== CACHE && n !== IMAGE_CACHE)
          .map((n) => caches.delete(n)),
      );
      await self.clients.claim();
    })(),
  );
});

/** Hosting serves /bills from bills.html, so the cache has to look there too. */
function candidates(pathname) {
  if (pathname === "/" || pathname === "") return ["/index.html"];
  const clean = pathname.replace(/\\/$/, "");
  return [pathname, clean + ".html", clean + "/index.html", "/index.html"];
}

async function fromCache(urls) {
  const cache = await caches.open(CACHE);
  for (const url of urls) {
    const hit = await cache.match(url);
    if (hit) return hit;
  }
  return null;
}

function isProductImage(url) {
  return IMAGE_HOSTS.some((host) => url.hostname === host || url.hostname.endsWith("." + host));
}

/**
 * Product photos, cache-first. A Storage download URL carries a token and
 * never changes content, so a hit is always good; the cache key drops the
 * query so a re-issued token doesn't orphan the copy already stored.
 */
async function productImage(request, url) {
  const key = url.origin + url.pathname;
  const cache = await caches.open(IMAGE_CACHE);
  const hit = await cache.match(key);
  if (hit) return hit;

  const response = await fetch(request);
  if (response.ok) {
    await cache.put(key, response.clone());
    const keys = await cache.keys();
    for (const stale of keys.slice(0, Math.max(0, keys.length - MAX_IMAGES))) {
      await cache.delete(stale);
    }
  }
  return response;
}

/**
 * Page loads: the network first, with a deadline, then the cached shell.
 *
 * This used to be cache-first, which meant the first load after every deploy
 * served the *previous* build — the new worker only finished installing after
 * the old page had already rendered. A shop would be told a fix was live and
 * still be looking at yesterday's app. Only the HTML takes this path; the
 * content-hashed chunks below stay cache-first, so boot is still fast.
 */
async function navigate(request, url) {
  const keys = candidates(url.pathname);
  try {
    // \`cache: "reload"\` skips the browser's own HTTP cache. Without it a host
    // serving HTML with a max-age (Firebase's default is an hour) would answer
    // from that cache and a deploy would take an hour to reach the shop, even
    // though this fetch is "network-first".
    const fresh = new Request(request.url, { cache: "reload", credentials: "same-origin" });
    const response = await withTimeout(fetch(fresh), NAVIGATION_TIMEOUT_MS);
    if (response && response.ok) {
      const cache = await caches.open(CACHE);
      await cache.put(keys[0], response.clone());
      return response;
    }
  } catch {
    // Offline, or the wifi is too slow to wait for — fall through to cache.
  }

  const cached = await fromCache(keys);
  if (cached) return cached;
  return fetch(request);
}

function withTimeout(promise, ms) {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error("timeout")), ms);
    promise.then(
      (value) => {
        clearTimeout(timer);
        resolve(value);
      },
      (err) => {
        clearTimeout(timer);
        reject(err);
      },
    );
  });
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);

  // The one cross-origin exception: without this the shop's product photos
  // vanish the moment the wifi drops, which is when the grid matters most.
  if (isProductImage(url)) {
    event.respondWith(productImage(request, url));
    return;
  }

  // Firestore, Auth and the callable functions are cross-origin and must never
  // be intercepted — the SDK does its own offline queueing.
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(navigate(request, url));
    return;
  }

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const cached = await cache.match(url.pathname);
      if (cached) return cached;
      try {
        const response = await fetch(request);
        // Content-hashed assets never change under the same URL, so anything
        // fetched successfully is worth keeping for the next outage.
        if (response.ok && url.pathname.startsWith("/_next/")) {
          await cache.put(url.pathname, response.clone());
        }
        return response;
      } catch (err) {
        const fallback = await cache.match(url.pathname);
        if (fallback) return fallback;
        throw err;
      }
    })(),
  );
});
`;

await writeFile(SW_PATH, sw, "utf8");
console.log(`sw.js written — ${urls.length} files precached (cache bakeshop-${version})`);
